name: Flutter Web

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x" # you can use 1.12
          channel: "stable" # Currently you have to use beta channel for Flutter web.
      - name: Upgrades Flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - name: Install Dependencies
        run: flutter packages get
      - name: Build Web
        run: flutter build web
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
 