name: Flutter Web

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.22.x", "3.24.x"]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          channel: "stable" # Currently you have to use beta channel for Flutter web.
      - name: Upgrades Flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - name: Install Dependencies
        run: flutter packages get
      - name: Build Web
        run: flutter build web --wasm
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: matrix.version == '3.24.x'
        with:
          folder: build/web
